/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups.$groupId.index'
import { Route as GroupsGroupIdTvRouteImport } from './routes/groups.$groupId.tv'
import { Route as GroupsGroupIdMembersRouteImport } from './routes/groups.$groupId.members'
import { Route as GroupsGroupIdMatchesRouteImport } from './routes/groups.$groupId.matches'
import { Route as GroupsGroupIdPlayersPlayerIdRouteImport } from './routes/groups.$groupId.players.$playerId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdTvRoute = GroupsGroupIdTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdMembersRoute = GroupsGroupIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdMatchesRoute = GroupsGroupIdMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdPlayersPlayerIdRoute =
  GroupsGroupIdPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/$groupId/matches': typeof GroupsGroupIdMatchesRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/tv': typeof GroupsGroupIdTvRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/players/$playerId': typeof GroupsGroupIdPlayersPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/groups/$groupId/matches': typeof GroupsGroupIdMatchesRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/tv': typeof GroupsGroupIdTvRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/players/$playerId': typeof GroupsGroupIdPlayersPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite': typeof InviteRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/$groupId/matches': typeof GroupsGroupIdMatchesRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/tv': typeof GroupsGroupIdTvRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
  '/groups/$groupId/players/$playerId': typeof GroupsGroupIdPlayersPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite'
    | '/join'
    | '/reset-password'
    | '/settings'
    | '/groups/$groupId'
    | '/groups/$groupId/matches'
    | '/groups/$groupId/members'
    | '/groups/$groupId/tv'
    | '/groups/$groupId/'
    | '/groups/$groupId/players/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite'
    | '/join'
    | '/reset-password'
    | '/settings'
    | '/groups/$groupId/matches'
    | '/groups/$groupId/members'
    | '/groups/$groupId/tv'
    | '/groups/$groupId'
    | '/groups/$groupId/players/$playerId'
  id:
    | '__root__'
    | '/'
    | '/invite'
    | '/join'
    | '/reset-password'
    | '/settings'
    | '/groups/$groupId'
    | '/groups/$groupId/matches'
    | '/groups/$groupId/members'
    | '/groups/$groupId/tv'
    | '/groups/$groupId/'
    | '/groups/$groupId/players/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteRoute: typeof InviteRoute
  JoinRoute: typeof JoinRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/tv': {
      id: '/groups/$groupId/tv'
      path: '/tv'
      fullPath: '/groups/$groupId/tv'
      preLoaderRoute: typeof GroupsGroupIdTvRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/members': {
      id: '/groups/$groupId/members'
      path: '/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof GroupsGroupIdMembersRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/matches': {
      id: '/groups/$groupId/matches'
      path: '/matches'
      fullPath: '/groups/$groupId/matches'
      preLoaderRoute: typeof GroupsGroupIdMatchesRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/players/$playerId': {
      id: '/groups/$groupId/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/groups/$groupId/players/$playerId'
      preLoaderRoute: typeof GroupsGroupIdPlayersPlayerIdRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
  }
}

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdMatchesRoute: typeof GroupsGroupIdMatchesRoute
  GroupsGroupIdMembersRoute: typeof GroupsGroupIdMembersRoute
  GroupsGroupIdTvRoute: typeof GroupsGroupIdTvRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
  GroupsGroupIdPlayersPlayerIdRoute: typeof GroupsGroupIdPlayersPlayerIdRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdMatchesRoute: GroupsGroupIdMatchesRoute,
  GroupsGroupIdMembersRoute: GroupsGroupIdMembersRoute,
  GroupsGroupIdTvRoute: GroupsGroupIdTvRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
  GroupsGroupIdPlayersPlayerIdRoute: GroupsGroupIdPlayersPlayerIdRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteRoute: InviteRoute,
  JoinRoute: JoinRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
